# Generated by Django 5.0.6 on 2024-11-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Clients',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Projects',
        ),
    ]
